/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youtubevideodownloader.ui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import youtubevideodownloader.model.VideoInfo;
import youtubevideodownloader.model.VideoInfoTableModel;
import youtubevideodownloader.rendrers.VideoItemTableCelRendererlEditor;
import youtubevideodownloader.rendrers.VideoListCellRenderer;

/**
 *
 * @author Filippo
 */
public class VideoDownloaderView extends javax.swing.JFrame {
    private final VideoInfoTableModel model;
    private final DefaultListModel<VideoInfo> listModel;

    /**
     * Creates new form VideoDownloaderView
     */
    public VideoDownloaderView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Youtube Videos downloader");
        
//        Object[][] rows = { { "", "", "" }, { "", "", "" }, { "", "", "" }, { "", "", "" } };
//        model = new DefaultTableModel();
//        model.addColumn("Test");
        ArrayList<VideoInfo> videoInfos = new ArrayList<>();
        videoInfos.add(new VideoInfo("Filippo1"));
        videoInfos.add(new VideoInfo("Filippo2"));
        videoInfos.add(new VideoInfo("Filippo3"));
        videoInfos.add(new VideoInfo("Filippo4"));
        videoInfos.add(new VideoInfo("Filippo5"));
        videoInfos.add(new VideoInfo("Filippo6"));
        videoInfos.add(new VideoInfo("Filippo7"));
        videoInfos.add(new VideoInfo("Filippo8"));
        videoInfos.add(new VideoInfo("Filippo9"));
        this.model = new VideoInfoTableModel(videoInfos);
        this.model.addRow(new VideoInfo("Filippo10"));
        
        this.listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        jList1.setCellRenderer(new VideoItemDetailView());
        this.listModel.addElement(new VideoInfo("filippo"));
        this.listModel.addElement(new VideoInfo("filippo"));
        this.listModel.addElement(new VideoInfo("filippo"));
        this.listModel.addElement(new VideoInfo("filippo"));
        
        VideoItemTableCelRendererlEditor cellRenderer = new VideoItemTableCelRendererlEditor();
//        jTable1.setDefaultRenderer(Object.class, cellRenderer);
//        jTable1.setDefaultEditor(Object.class, cellRenderer.getEditor());
////        jTable1.setShowGrid(true);
//        jTable1.setGridColor(Color.gray);
//        jTable1.setRowHeight(120);
//        jTable1.setModel(model);
        
        
        Vector<VideoInfo> vector = new Vector<>();
        vector.add(new VideoInfo("Filippo"));
        
        
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
//        model.addRow(vector);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoDownloaderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoDownloaderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoDownloaderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoDownloaderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VideoDownloaderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
